# Species that do well all over

Almost anywhere in Norman that's sunny and not touching standing water
- Maximilian sunflower\index{sunflower!Maximilian}

## Shady\index{shade} habitats

-   White avens

-   Lyre Leaf sage

-   Inland Sea Oats

-   Frostweed

-   Texas mallow

-   Fall obedient plant

-   Horseherb

-   Purpletop grass

## Sunny habitats

If you have the red clay soil\index{soil!red clay}and live on the "north" (loosely north) side of town, these are your keystone plants:

-   Maximilian sunflower

-   Rudbeckia

-   Little bluestem

-   Showy evening primrose

Sandy loams (not sticky clay, doesn't have giant cracks form in summer dry), but not loose sand

-   Maximilian sunflower

-   Rudbeckia

-   Winecups

-   Frogfruit

-   Showy evening primrose @sec-pinkladies

-   Fluttermill primrose @sec-fluttermill

-   Common annual sunflower

If you have sandy soil\index{soil!sandy} and elsewhere in town, plant these:

-   Monarda punctata

-   Spiderwort (which one?)

-   Little bluestem

-   Gaillardia aestivalis

-   Tall thistle

Dark clay\index{soil!black gumbo}

-   I need to ask J/J what grows in their yard.

For more species and what they like, see @sec-species.
